# Generated by Django 6.0.4 on 2026-04-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('editorial', models.CharField(max_length=30)),
                ('fecha_publicacion', models.DateField()),
                ('portada', models.ImageField(blank='true', null='true', upload_to='portadas/')),
            ],
        ),
    ]
