# Generated by Django 6.0.4 on 2026-04-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='hobbies',
            field=models.TextField(blank=True),
        ),
    ]
