# Generated by Django 6.0.4 on 2026-04-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='fecha_de_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
